### ISSUE TITLE
Uninstall command in readme

### ISSUE THREAD

**Issue by Pawan-Johnson** [EnderIce2/WhatsApp-Wine#2]
Could you please add an uninstall command in the readme

**Comment by EnderIce2** [comment]
If you want to uninstall it, just run `./whatsapp-wine.sh` and then select the option "Uninstall" (U key).
Or uninstall manually by removing `/home/$USER/.local/share/applications/wine-whatsapp.desktop`, `/home/$USER/<prefix name>` and `/home/$USER/.config/WhatsApp-wine`. Hope this help.
